# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "linting"
          command: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      run: echo "Hello world from test"

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      run: echo "Hello worl from analyzes"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploying-react:
    jobs:
      - build
      # - test:
      #     requires: build
      # - analyze:
      #     requires: test