  # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
default: &jobImageDefaults
  docker:
  - image: circleci/node:13.8.0

jobs:
  build:
    <<: *jobImageDefaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  tests:
    <<: *jobImageDefaults
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    <<: *jobImageDefaults
    steps:
      - checkout
      - run: npm audit
  print_var:
    <<: *jobImageDefaults
    environment:
      CIRCLE_COMPARE_URL: "initiated"
    working_directory: ~/main
    steps:
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo "changed" > $CIRCLE_COMPARE_URL
      - run: echo $CIRCLE_COMPARE_URL
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  cistages_almost_complete:
    # Run the welcome/run job in its own container
    jobs:
      - print_var
      # - build
      # - tests:
      #     requires:
      #     - build
      # - analyze:
      #     requires:
      #     - tests

