# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "linting"
          command: |
            npm i
            npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: 
        name: "testing with npm"
        command: |
          echo "executing forseen tests"
          npm i
          npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: 
          name: "analyzing npm module" 
          command: | 
            echo "Verification before deploy"
            npm i
            npm audit

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploying-react:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires: 
            - test